language: objective-c
osx_image: xcode8.2

branches:
  only:
  - develop

script:
  - xcodebuild clean build -sdk iphonesimulator -project Sweep.xcodeproj -scheme SweepTests -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' CODE_SIGNING_REQUIRED=NO test